"""Service Retention dashboard (Power BI-style readout) from retention_report.json."""
from __future__ import annotations

import json
from pathlib import Path

R = json.loads(Path("reports/retention_report.json").read_text())
kpis = R["service_retention_kpis"]
drivers = R["retention_drivers"]
actions = R["prescriptive"]["action_mix"]
metrics = R["model_metrics"]

top_drivers = list(drivers.items())[:6]
data = {
    "region_labels": list(kpis["by_region"].keys()), "region_vals": list(kpis["by_region"].values()),
    "warr_labels": list(kpis["by_warranty"].keys()), "warr_vals": list(kpis["by_warranty"].values()),
    "driver_labels": [d[0] for d in top_drivers], "driver_vals": [d[1] for d in top_drivers],
    "action_labels": list(actions.keys()), "action_vals": list(actions.values()),
}

html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Service Retention Analytics</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
 body{{font-family:'Segoe UI',system-ui,sans-serif;background:#f6f7fb;color:#1c2333;margin:0}}
 header{{background:#1a1a2e;color:#fff;padding:16px 30px}} h1{{font-size:20px;margin:0}}
 .sub{{color:#b8b8d0;font-size:13px}}
 main{{max-width:1150px;margin:22px auto;padding:0 18px}}
 .kpis{{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin-bottom:20px}}
 .kpi{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px}}
 .kpi .l{{color:#6b7280;font-size:13px}}.kpi .v{{font-size:24px;font-weight:700;margin-top:4px}}
 .kpi.good .v{{color:#14804a}} .kpi.warn .v{{color:#b42318}}
 .grid{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}
 .panel{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:18px}}
 .panel h2{{font-size:15px;margin:0 0 12px}} canvas{{max-height:270px}}
 @media(max-width:800px){{.grid{{grid-template-columns:1fr}}}}
 footer{{color:#6b7280;font-size:12px;text-align:center;margin:26px 0}}
</style></head><body>
<header><h1>Service Retention Analytics</h1>
<div class="sub">Aftersales · predictive churn model · retention drivers · prescriptive outreach</div></header>
<main>
<div class="kpis">
 <div class="kpi good"><div class="l">Service retention rate</div><div class="v">{kpis['overall_retention_rate_pct']}%</div></div>
 <div class="kpi"><div class="l">Churn model AUC</div><div class="v">{metrics['churn_roc_auc']}</div></div>
 <div class="kpi"><div class="l">Lift @ top-10% risk</div><div class="v">{metrics['lift_at_10pct']}x</div></div>
 <div class="kpi warn"><div class="l">At-risk customers</div><div class="v">{R['prescriptive']['at_risk_customers']:,}</div></div>
</div>
<div class="grid">
 <div class="panel"><h2>Retention rate by region (%)</h2><canvas id="c1"></canvas></div>
 <div class="panel"><h2>Retention by warranty status (%)</h2><canvas id="c2"></canvas></div>
</div>
<div class="grid">
 <div class="panel"><h2>Top retention drivers (model importance)</h2><canvas id="c3"></canvas></div>
 <div class="panel"><h2>Prescribed outreach action mix</h2><canvas id="c4"></canvas></div>
</div>
</main>
<footer>Synthetic data · generated by src/retention/build_retention_dashboard.py</footer>
<script>
const D={json.dumps(data)};
new Chart(c1,{{type:'bar',data:{{labels:D.region_labels,datasets:[{{data:D.region_vals,backgroundColor:'#1a1a2e'}}]}},options:{{plugins:{{legend:{{display:false}}}},scales:{{y:{{min:0,max:100}}}}}}}});
new Chart(c2,{{type:'bar',data:{{labels:D.warr_labels,datasets:[{{data:D.warr_vals,backgroundColor:'#14804a'}}]}},options:{{plugins:{{legend:{{display:false}}}},scales:{{y:{{min:0,max:100}}}}}}}});
new Chart(c3,{{type:'bar',data:{{labels:D.driver_labels,datasets:[{{data:D.driver_vals,backgroundColor:'#2749c9'}}]}},options:{{indexAxis:'y',plugins:{{legend:{{display:false}}}}}}}});
new Chart(c4,{{type:'doughnut',data:{{labels:D.action_labels,datasets:[{{data:D.action_vals,backgroundColor:['#1a1a2e','#2749c9','#14804a','#e8a33d','#b42318','#7c5cd6']}}]}}}});
</script></body></html>"""
Path("reports").mkdir(exist_ok=True)
Path("reports/retention_dashboard.html").write_text(html, encoding="utf-8")
print("Dashboard written to reports/retention_dashboard.html")
