"""Reporting layer: query the star schema, emit a self-contained HTML dashboard.

Stands in for the Qlik/Cognos consumption layer — same pattern: the dashboard
reads only curated KPIs from the warehouse, never source files.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

DB = "data/warehouse.db"
OUT = "reports/dashboard.html"

TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Dealer Service Analytics</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
 body{font-family:'Segoe UI',system-ui,sans-serif;background:#f6f7fb;color:#1c2333;margin:0}
 header{background:#fff;border-bottom:1px solid #e5e7eb;padding:16px 30px}
 h1{font-size:20px;margin:0} .sub{color:#6b7280;font-size:13px}
 main{max-width:1150px;margin:22px auto;padding:0 18px}
 .kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px;margin-bottom:20px}
 .kpi{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px}
 .kpi .l{color:#6b7280;font-size:13px}.kpi .v{font-size:26px;font-weight:700;margin-top:4px}
 .grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}
 .panel{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:18px}
 .panel h2{font-size:15px;margin:0 0 12px} canvas{max-height:270px}
 @media(max-width:800px){.grid{grid-template-columns:1fr}}
 footer{color:#6b7280;font-size:12px;text-align:center;margin:26px 0}
</style></head><body>
<header><h1>Dealer Service Analytics</h1>
<div class="sub">Curated data product · star schema · refreshed from warehouse.db</div></header>
<main>
<div class="kpis">
 <div class="kpi"><div class="l">Repair orders (validated)</div><div class="v">__N_ROS__</div></div>
 <div class="kpi"><div class="l">Fixed first visit</div><div class="v">__FFV__%</div></div>
 <div class="kpi"><div class="l">Avg satisfaction</div><div class="v">__CSAT__ / 5</div></div>
 <div class="kpi"><div class="l">Customer-pay revenue</div><div class="v">$__REV__M</div></div>
</div>
<div class="grid">
 <div class="panel"><h2>Fixed-first-visit rate by region</h2><canvas id="c1"></canvas></div>
 <div class="panel"><h2>Satisfaction vs days to close</h2><canvas id="c2"></canvas></div>
</div>
<div class="panel"><h2>Warranty spend vs customer-pay revenue by month</h2><canvas id="c3"></canvas></div>
<div class="panel"><h2>Recall share by model</h2><canvas id="c4"></canvas></div>
</main>
<footer>Synthetic data · generated by src/build_dashboard.py from the governed warehouse</footer>
<script>
const D = __DATA__;
new Chart(c1,{type:'bar',data:{labels:D.region.labels,datasets:[{data:D.region.values,backgroundColor:'#2749c9'}]},options:{plugins:{legend:{display:false}},scales:{y:{min:80,max:90}}}});
new Chart(c2,{type:'line',data:{labels:D.cycle.labels,datasets:[{data:D.cycle.values,borderColor:'#b42318',backgroundColor:'rgba(180,35,24,.1)',fill:true,tension:.3}]},options:{plugins:{legend:{display:false}}}});
new Chart(c3,{type:'bar',data:{labels:D.mix.labels,datasets:[
 {label:'Warranty spend',data:D.mix.warranty,backgroundColor:'#7c5cd6'},
 {label:'Customer-pay revenue',data:D.mix.customer,backgroundColor:'#2ca86b'}]},
 options:{scales:{x:{stacked:true},y:{stacked:true}}}});
new Chart(c4,{type:'bar',data:{labels:D.recall.labels,datasets:[{data:D.recall.values,backgroundColor:'#e8a33d'}]},options:{indexAxis:'y',plugins:{legend:{display:false}}}});
</script></body></html>"""


def q(conn, sql):
    return conn.execute(sql).fetchall()


def main() -> None:
    conn = sqlite3.connect(DB)
    n_ros = q(conn, "SELECT COUNT(*) FROM fact_repair_orders")[0][0]
    ffv = q(conn, "SELECT ROUND(100.0*SUM(repeat_repair_flag=0)/COUNT(*),1) FROM fact_repair_orders")[0][0]
    csat = q(conn, "SELECT ROUND(AVG(satisfaction_score),2) FROM fact_repair_orders "
                   "WHERE satisfaction_score IS NOT NULL")[0][0]
    rev = q(conn, "SELECT ROUND(SUM(total_amount)/1e6,1) FROM fact_repair_orders WHERE pay_type='customer'")[0][0]

    region = q(conn, """SELECT dd.region, ROUND(100.0*SUM(f.repeat_repair_flag=0)/COUNT(*),1)
        FROM fact_repair_orders f JOIN dim_dealer dd USING(dealer_key) GROUP BY dd.region ORDER BY 2 DESC""")
    cycle = q(conn, """SELECT days_to_close, ROUND(AVG(satisfaction_score),2) FROM fact_repair_orders
        WHERE satisfaction_score IS NOT NULL GROUP BY days_to_close ORDER BY days_to_close""")
    mix = q(conn, """SELECT d.month_name,
        ROUND(SUM(CASE WHEN pay_type='warranty' THEN total_amount ELSE 0 END)/1000,1),
        ROUND(SUM(CASE WHEN pay_type='customer' THEN total_amount ELSE 0 END)/1000,1)
        FROM fact_repair_orders f JOIN dim_date d ON d.date_key=f.open_date_key
        GROUP BY d.year, d.month ORDER BY d.year, d.month""")
    recall = q(conn, """SELECT dv.model, ROUND(100.0*SUM(f.service_type='recall')/COUNT(*),1)
        FROM fact_repair_orders f JOIN dim_vehicle dv USING(vehicle_key)
        GROUP BY dv.model ORDER BY 2 DESC""")

    data = {
        "region": {"labels": [r[0] for r in region], "values": [r[1] for r in region]},
        "cycle": {"labels": [r[0] for r in cycle], "values": [r[1] for r in cycle]},
        "mix": {"labels": [r[0] for r in mix], "warranty": [r[1] for r in mix], "customer": [r[2] for r in mix]},
        "recall": {"labels": [r[0] for r in recall], "values": [r[1] for r in recall]},
    }
    html = (TEMPLATE.replace("__N_ROS__", f"{n_ros:,}").replace("__FFV__", str(ffv))
            .replace("__CSAT__", str(csat)).replace("__REV__", str(rev))
            .replace("__DATA__", json.dumps(data)))
    Path(OUT).parent.mkdir(parents=True, exist_ok=True)
    Path(OUT).write_text(html, encoding="utf-8")
    print(f"Dashboard written to {OUT}")


if __name__ == "__main__":
    main()
